// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1KzYDhn9Y7X_VltsL4xkh6X-nJZx6iR4',
    appId: '1:760562010684:android:5120201efc97f2c9655139',
    messagingSenderId: '760562010684',
    projectId: 'bounce-tower',
    storageBucket: 'bounce-tower.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5m9LCCjDpGX8GJADkpJ170mlMYNegBK8',
    appId: '1:760562010684:ios:451a67d627acd908655139',
    messagingSenderId: '760562010684',
    projectId: 'bounce-tower',
    storageBucket: 'bounce-tower.firebasestorage.app',
    androidClientId: '760562010684-62otmraprapj0jhamlf02ajholvkkh9b.apps.googleusercontent.com',
    iosClientId: '760562010684-mcgfui8p8bqm02a34h93tfi4b1aetfpp.apps.googleusercontent.com',
    iosBundleId: 'com.bouncetower.bounceTower',
  );
}
